SIZE = 25

ROWS_IN_BOARD = 25
COLS_IN_BOARD = 50

PIXEL_ROWS = ROWS_IN_BOARD * SIZE
PIXEL_COLS = COLS_IN_BOARD * SIZE
#
SOLDIER_START = (0, 0)

BUSH_BOMB_NUM = 20

ITEM_PROPORTION = {
    'soldier': (2, 4),
    'mine': (3, 1),
    'grass': (3, 1),
    'flag': (4, 3)
}


FLAG = (COLS_IN_BOARD - ITEM_PROPORTION['flag'][0], ROWS_IN_BOARD - ITEM_PROPORTION['flag'][1])

GREEN = (64, 200, 45)
